info:
  contact: {}
  title: personal projects
  version: "1.0"
paths:
  /api/v1/projects:
    post:
      parameters:
      - description: project name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses: {}
swagger: "2.0"
